### ISSUE TITLE
Deserialization Issues using Standard MsgPack Javascript library

### ISSUE THREAD

**Issue by tommybutler** [jacquesg/p5-MsgPack-Raw#2]
Certain datastructures won't deserialize correctly using the standard MsgPack JavaScript library (msgpack.org)

This datastructure deserializes just fine:
`perl -MMsgPack::Raw -E 'say MsgPack::Raw::Packer->new->pack( { a => 1, b => 2 } )'`

While this one will not:
`perl -MMsgPack::Raw -E 'say MsgPack::Raw::Packer->new->pack( {"foo" => "bar"} )'`

And this one will not:
`perl -MMsgPack::Raw -E 'say MsgPack::Raw::Packer->new->pack( { "foo" => "bar", baz => [ 2.4, 7, "wibble", { "color" => "red", "theskyis" => "blue " } ] } )'`

The issue appears to happen when any value in a dictionary is something other than an integer.  No exceptions thrown, but the deserialization yields an object with key values that don't completely deserialize.  To the best of my knowledge, this doesn't happen when encoding similar datastructures using standard MsgPack libraries in other languages.  Here is the result of deserialization:

```
{
    "baz": [
        2.4,
        7,
        {
            "type": "Buffer",
            "data": [
                119,
                105,
                98,
                98,
                108,
                101
            ]
        },
        {
            "theskyis": {
                "type": "Buffer",
                "data": [
                    98,
                    108,
                    117,
                    101,
                    32
                ]
            },
            "color": {
                "type": "Buffer",
                "data": [
                    114,
                    101,
                    100
                ]
            }
        }
    ],
    "foo": {
        "type": "Buffer",
        "data": [
            98,
            97,
            114
        ]
    }
}
```

Here is the HTML code where the deserialization is peformed:
```
html>
   <head>
      <title>MessagePack Testing</title>

      <script
         integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
         crossorigin="anonymous"></script>

      <script>
         $( init_all )

         function init_all ()
         {
             const req = new XMLHttpRequest();
             req.open("GET", "/msg.bin", true);
             req.responseType = "arraybuffer";
             req.onload = (event) => {
               const data = new Uint8Array(req.response);
               console.log( msgpack.decode(data) );
             };
             req.send(null);
         }
      </script>

   </head>
   <body>
      <h1>Hello MessagePack World</h1>
   </body>
</html>

```

I'm not entirely certain whether or not the problem lies in the packing or in the unpacking, but I would appreciate any thoughts and feedback anyone can offer.

**Comment by tommybutler** [comment]
I resolved the issue by using a different Perl library with utf8 support.

**Comment by jacquesg** [comment]
I believe you're confusing utf-8 support and the library. This library, is exactly the same as the one you're using, the API is subtly different.
